### ISSUE TITLE
Option fields handling

### ISSUE THREAD

**Issue by MrBan** [cvogt/play-json-extensions#13]
I've noticed a different behavior between `jsonx` format and standard json format when dealing with Option fields. In the example below, the first `fromJson` conversion returns a `JsError`  while the second call returns `JsSuccess`. In my opinion the first behavior is the correct one since the JSON object is invalid.

This is relative to version 0.2. I know it is quite old, but if you could provide any clue on how to fix it I would really appreciate it :)

    import org.cvogt.play.json.Jsonx
    import play.api.libs.json._

    case class C1(v: Option[String])
    case class C2(v: Option[String])

    implicit val c1JsonFormat = Json.format[C1]
    implicit val c2JsonFormat = Jsonx.formatCaseClass[C2]

    val json = Json.obj("v" -> 11)

    Json.fromJson[C1](json)  // this returns JsError
    Json.fromJson[C2](json)  // this returns JsSuccess

Thanks

**Comment by cvogt** [comment]
@MrBan thx, will look into it.

**Comment by cvogt** [comment]
haven't forgotten about this, trying to get to it very soon

**Comment by MrBan** [comment]
Thanks a lot :)

**Comment by cvogt** [comment]
So my investigations show that this magically got fixed in e95cd47, in the upgrade from play-json 2.3 to play-json 2.4. This was shortly before the 0.3.0 release. If I knew why this was broken and how to fix it, I would release a 0.2.1, but since the fix somehow came with play-json 2.4.1, I would suggest to upgrade to the latest play-json-extensions 0.6.0. Probably a good idea anyways :).

**Comment by cvogt** [comment]
Since it works since 0.3.0 I am closing this
